### ISSUE TITLE
Weird links on the wiki?

### ISSUE THREAD

**Issue by gledinski** [PureDarwin/PureDarwin#107]
While I was going through the wiki, I noticed some weird links being present, such as DJ software. Is this intentional? 

![image](https://user-images.githubusercontent.com/56172613/147398537-5334f88c-acd1-45a8-bee5-ff2cf329253b.png)

**Comment by ninjadev64** [comment]
Hope this explains it. 
![image](https://user-images.githubusercontent.com/63245705/152038243-5cde9488-2584-431c-96fc-8dd111c03565.png)

**Comment by mglebinski** [comment]
I appreciate a response, I think giving randoms the ability to the wiki (probably) isn't a good thing.

**Comment by ninjadev64** [comment]
Can this be closed?
