### ISSUE TITLE
Domain issues

### ISSUE THREAD

**Issue by ninjadev64** [PureDarwin/PureDarwin#109]
http://puredarwin.org/ - a Google 404, presumably related to the old Google Site, should redirect to www.
http://www.puredarwin.org/ - does not redirect to the HTTPS version, enable Enforce HTTPS in GitHub Pages settings

**Comment by ninjadev64** [comment]
Also, you should change the Twitter profile picture to the BSD daemon spin-off https://twitter.com/puredarwin

**Comment by CodeAsm** [comment]
> http://puredarwin.org/ - a Google 404, presumably related to the old Google Site, should redirect to [www](http://www). http://www.puredarwin.org/ - does not redirect to the HTTPS version, enable Enforce HTTPS in GitHub Pages settings

Site seems to work now. but some stuff here on the github seems broken. 
https://gitter.im/PureDarwin/ is dead, linked from all the way down https://github.com/PureDarwin/PureDarwin/wiki

**Comment by wjk** [comment]
The wiki footer has been fixed. I have no control over puredarwin.org or any social media accounts. I would ask @csekel, who is hereby pinged, but you might not get a response.

**Comment by ninjadev64** [comment]
@wjk On a seperate note, the Discord community is relatively active and we've been excited to see your recent changes! If you'd like to join, the link is https://discord.gg/9kz8XXRRcT - if you don't feel comfortable with getting a Discord account, then let me know when you're available to link the Matrix channel with the Discord server, as a Matrix admin is required to perform that action :)

**Comment by ninjadev64** [comment]
> The wiki footer has been fixed. I have no control over puredarwin.org or any social media accounts. I would ask @csekel, who is hereby pinged, but you might not get a response.

I believe you should be able to enable "Enforce HTTPS" on the puredarwin.github.io repository under "Pages" settings, though.

**Comment by wjk** [comment]
Enforce HTTPS has been enabled for the Pages site. I am going to close this issue now.
