### ISSUE TITLE
Utilize/Combine Efforts with HelloSystem for a better bootable ISO and user experience?

### ISSUE THREAD

**Issue by iamhumanipromise** [PureDarwin/PureDarwin#110]
[Hello System](https://github.com/helloSystem) aims to be a user friendly BSD. 

Why it is not based on Darwin? Don’t know but that saddens. Hopefully the two projects can unify on a base of compatible installers and user space experiences to be able to benefit from one another.

**Comment by bnaambo** [comment]
I hope it never unify with those paranoid guys of hello system :dagger:

**Comment by iamhumanipromise** [comment]
Well, perhaps not unify but perhaps be agreed upon so things like... a nice installer, out of box GUI, etc can be possible.

**Comment by louies0623** [comment]
I also agree that there should be a GUI, so that users who want to know what Drawin is can easily experience it. If hello system is not good, then GNUstep or XFCE are the channels for users to get started. "The real genius of the system is you You don’t have to be a genius to use it.”

**Comment by Daasin** [comment]
I'd agree because it's a very good looking UI that could be paired with the very interesting Darwin base

**Comment by KevDoy** [comment]
This should be in Discussions not Issues.
