### ISSUE TITLE
How to build the latest code?

### ISSUE THREAD

**Issue by narukeu** [PureDarwin/PureDarwin#118]
I'm using a Mac with Apple Silicon and I've downloaded the latest source code from GitHub.
I tried to compile it after fixing the dependencies and found that it didn't work, the software told me it couldn't be compiled on the arm64 architecture, then I tried to fix the error with "make ARCH=x86_64" and found that that didn't work either. I have looked through the wiki and found no useful information.

**Comment by narukeu** [comment]
I am trying to build xnu kernel only via "make xnu" command,but it said:

```
[ 95%] Performing build step for 'xnu_headers.extproj'
make[4]: *** No rule to make target `installhdrs'.  Stop.
make[3]: *** [src/Kernel/xnu/xnu_header_build/src/xnu_headers.extproj-stamp/xnu_headers.extproj-build] Error 2
make[2]: *** [src/Kernel/xnu/CMakeFiles/xnu_headers.extproj.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 95%] Linking CXX executable host_ld
[ 95%] Built target host_ld
make[1]: *** [src/Kernel/xnu/CMakeFiles/xnu.dir/rule] Error 2
make: *** [xnu] Error 2
```

**Comment by narukeu** [comment]
I tried to do the same work with an Intel Mac, but it appears the same problem as the previous comment.
Is this problem caused by a problem with the source code itself?

**Comment by pygeniusgithub** [comment]
maybe it happens because you are trying to build the system on **_apple silicon_** but you maybe need to try build on intel
