### ISSUE TITLE
Unable to build: No rule to make target `installhdrs'.  Stop.

### ISSUE THREAD

**Issue by ninjadev64** [PureDarwin/PureDarwin#136]
## Steps taken
- Installed latest CMake from CMake.org
- Installed latest Homebrew from brew.sh
- Installed latest openssl from Homebrew
- Cloned latest PureDarwin sources from this repo
- Ran `cmake -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl` in project root directory to generate and configure
- Ran `make` in project root directory *twice*

## Output of second run of Make
```
PureDarwin % make
[  3%] Built target host_libxar
[  9%] Built target host_libstuff
[ 11%] Built target host_ld_helper
[ 11%] Built target host_ld_BlocksRuntime
[ 12%] Built target host_ld_libparsers
[ 14%] Built target host_ld_libpasses
[ 16%] Built target host_ld
[ 16%] Built target host_libmacho
[ 17%] Built target host_libtool
[ 17%] Built target unifdef
[ 17%] Built target host_lipo
[ 18%] Built target host_nm
[ 18%] Built target host_strip
[ 18%] Built target host_codesign_allocate
[ 19%] Built target host_ctf_insert
[ 19%] Built target host_nmedit
[ 22%] Built target libelf.host
[ 24%] Built target libctf.host
[ 28%] Built target libdwarf.host
[ 31%] Built target host_ctfconvert
[ 34%] Built target host_ctfmerge
[ 36%] Built target migcom
[ 37%] Performing build step for 'xnu_headers.extproj'
make[3]: *** No rule to make target `installhdrs'.  Stop.
make[2]: *** [src/Kernel/xnu/xnu_header_build/src/xnu_headers.extproj-stamp/xnu_headers.extproj-build] Error 2
make[1]: *** [src/Kernel/xnu/CMakeFiles/xnu_headers.extproj.dir/all] Error 2
make: *** [all] Error 2
```

### Output of `ls src/Kernel/xnu/CMakeFiles/xnu_headers.extproj.dir`
`DependInfo.cmake	Labels.json		Labels.txt		build.make		cmake_clean.cmake	compiler_depend.make	compiler_depend.ts	progress.make`

## System information
macOS Ventura 13.5.2 in an OSX-KVM virtual machine

@wjk

**Comment by wjk** [comment]
The problem is that you had CMake generate Makefiles in the project source directory, thus overwriting the Makefile in `src/Kernel/xnu` that CMake’s makefile is trying to call. You’ll need to make a subdirectory and configure CMake in there. Hope this helps!

**Comment by ninjadev64** [comment]
> The problem is that you had CMake generate Makefiles in the project source directory, thus overwriting the Makefile in `src/Kernel/xnu` that CMake’s makefile is trying to call. You’ll need to make a subdirectory and configure CMake in there. Hope this helps!

Thanks! It's my first time using CMake.

**Comment by ninjadev64** [comment]
My build has successfully completed, but I don't know what it's made. Could you point out the major components that have been built and where they're located?

**Comment by ninjadev64** [comment]
I see a list of them here, but for instance, where is the built image of xnu that it mentions?
```
build % make
[  3%] Built target host_libxar
[  9%] Built target host_libstuff
[ 11%] Built target host_ld_helper
[ 11%] Built target host_ld_BlocksRuntime
[ 12%] Built target host_ld_libparsers
[ 14%] Built target host_ld_libpasses
[ 16%] Built target host_ld
[ 16%] Built target host_libmacho
[ 17%] Built target host_libtool
[ 17%] Built target unifdef
[ 17%] Built target host_lipo
[ 18%] Built target host_nm
[ 18%] Built target host_strip
[ 18%] Built target host_codesign_allocate
[ 19%] Built target host_ctf_insert
[ 19%] Built target host_nmedit
[ 22%] Built target libelf.host
[ 24%] Built target libctf.host
[ 28%] Built target libdwarf.host
[ 31%] Built target host_ctfconvert
[ 34%] Built target host_ctfmerge
[ 36%] Built target migcom
[ 38%] Built target xnu_headers.extproj
[ 38%] Built target libkmod
[ 38%] Built target AppleAPIC
[ 39%] Built target AppleI386GenericPlatform
[ 41%] Built target IOATAFamily
[ 42%] Built target AppleIntelPIIXATA
[ 43%] Built target ApplePS2Controller
[ 44%] Built target IOACPIFamily
[ 45%] Built target IOPCIFamily
[ 45%] Built target ApplePIODMA
[ 47%] Built target IOStorageFamily
[ 49%] Built target IOStorageFamilyUserHeaders
[ 52%] Built target corecrypto.kext
[ 53%] Built target pthread.kext
[ 54%] Built target libfirehose_kernel
[ 55%] Built target xnu
[ 55%] Built target dyld_availability_headers
[ 55%] Built target CrashReporterClient
[ 55%] Built target libc_headers_gen_script
[ 63%] Built target corecrypto_shared
[ 63%] Built target corecrypto_user
[ 64%] Built target corecrypto_static
[ 64%] Generating libc-features.h
[ 64%] Built target libc_features
[ 90%] Built target libsystem_kernel_static
[ 92%] Built target libsystem_kernel
[ 93%] Built target host_checksyms
[ 93%] Built target host_size
[ 93%] Built target host_strings
[ 94%] Built target host_redo_prebinding
[ 94%] Built target host_seg_addr_table
[ 94%] Built target host_seg_hack
[ 94%] Built target host_install_name_tool
[ 95%] Built target host_indr
[ 96%] Built target host_segedit
[ 96%] Built target host_pagestuff
[ 96%] Built target host_bitcode_strip
[ 96%] Built target host_check_dylib
[ 96%] Built target host_cmpdylib
[ 96%] Built target host_inout
[ 97%] Built target host_vtool
[ 97%] Built target host_ranlib
[100%] Built target host_ctfdump
[100%] Built target host_xar
```

**Comment by wjk** [comment]
Go to the `src/Kernel/xnu` subdirectory of your build root. Inside there is another directory called `xnu`. This is supposed to represent the root directory of a filesystem and is what XNU’s makefile is installing into. Inside, you will find `System/Library/Kernels/kernel`. That’s your kernel.

**Comment by ninjadev64** [comment]
Awesome, thanks.

**Comment by ninjadev64** [comment]
Hey @wjk,

It's been a couple of days - I've been (and someone else on the Discord server) looking for an appropriate bootloader to boot the PureDarwin XNU kernel. The only two options we've discovered are GRUB and Chameleon/Enoch. Enoch is quite outdated and its only releases are 32-bit. We're not quite sure how to set up GRUB (the wiki has some instructions but are very outdated and assume GRUB has builtin support for Darwin which I doubt it kept for 15 years).

Do you know how to either compile PureDarwin 32-bit or set up GRUB to boot Darwin? (If you like, it may be easier to continue this discussion on Discord or Matrix).

**Comment by wjk** [comment]
> looking for an appropriate bootloader to boot the PureDarwin XNU kernel

Let’s continue this in #137.
