### ISSUE TITLE
Build PureDarwin using Darling (xcode cli only) support.

### ISSUE THREAD

**Issue by cursedUs64-git** [PureDarwin/PureDarwin#141]
As we can install Xcode on Darling, it could, infact, possible to use Darling xcode (cli only) for building PureDarwin.

**Comment by wjk** [comment]
@cursedUs64-git First of all, please forgive the delay in response. I have been going through some hard times personally.

As far as I can tell, you can already use Darling xcode to build PureDarwin. PureDarwin uses only the compiler, linker, `/usr/include` headers, and `/usr/lib` libraries from the macOS SDK. Any headers needed will be in this repo. Any tools needed will have their source in this repo. Hope this helps!
