### ISSUE TITLE
Important Note

### ISSUE THREAD

**Issue by wjk** [PureDarwin/PureDarwin#144]
I am currently taking an extended break from social media. If you wish to contact me or send me code, please do so here on GitHub and not on Discord. Thank you.

**Comment by ninjadev64** [comment]
Please consider making a Matrix (or Discord) account for the sole purpose of joining the PureDarwin communities. You need not join any other social spaces if that is your preference, but we would appreciate another team member in the discussions. @csekel has been making some good progress recently and there are some interesting discussions - we now have over 200 members on the Discord server, which is bridged to the Matrix rooms.

https://matrix.to/#/#puredarwin:matrix.org

**Comment by KevDoy** [comment]
@wjk There's been quite a bit of activity on the Discord, the [website](https://www.puredarwin.org) has been redone, @ninjadev64's [wiki](https://www.puredarwin.org/wiki/#/about/Wiki) has been implemented and is being overhauled. Curious if you're interested in coming to join the discussion.

Cheers!
