### ISSUE TITLE
how to build the vmdk file from source code?

### ISSUE THREAD

**Issue by iOSPrincekin** [PureDarwin/PureDarwin#147]
Hi,I run the pd_17_4.vmdk use qemu: 

qemu-system-x86_64 -m 8192 -cpu Penryn -smp 2  -netdev user,id=network0 -device rtl8139,netdev=network0 -serial stdio -drive format=vmdk,file=pd_17_4.vmdk

it works well, but how to build the  pd_17_4.vmdk file?

**Comment by wjk** [comment]
That vmdk file is ancient (as in decades old). We’re currently working on creating a VMDK of our own, but it’s slow going.

**Comment by iOSPrincekin** [comment]
> That vmdk file is ancient (as in decades old). We’re currently working on creating a VMDK of our own, but it’s slow going.

Can you post some wiki about how to create vmdk files or how to create bootable iso files, so that we can get involved and maybe help you

**Comment by KevDoy** [comment]
Issue is similar to #38, closing to remove duplicate.
