### ISSUE TITLE
Access to OS X - hosting providers etc.

### ISSUE THREAD

**Issue by voltagex** [PureDarwin/PureDarwin#2]
I have approached https://macstadium.com/ about whether they could provide an OS X build server or similar.

**Comment by hideout** [comment]
hello,

https://macstadium.com/ is a good choice i think my friend had a build
server there and
he only told me positiv feedback

cheers

2015-07-07 11:33 GMT+02:00 Adam Baxter <notifications@github.com>:

**Comment by voltagex** [comment]
Please note I am NOT endorsing one company over another. The Mac hosting
market is relatively small, and I am open to all suggestions.

**Comment by hideout** [comment]
hey adam,

no problem i just say that i heard about macstadium . i know that there
arent so much offers about mac hosting.
but we will see

do you use irc?

you are welcome to join our developer channel #puredarwin in freenode!

cheers


2015-07-07 12:53 GMT+02:00 Adam Baxter <notifications@github.com>:

**Comment by voltagex** [comment]
@vmlemon MacStadium have responded positively - they just require a logo / credit on the project page. See email for details.

**Comment by voltagex** [comment]
Moved to https://groups.google.com/forum/m/?fromgroups#!topic/puredarwin/Rf_K98kxq0Q
