### ISSUE TITLE
disk1s1s3: ioctl(_IOR,'d',77,4) is unsupported on PowerPC

### ISSUE THREAD

**Issue by probonopd** [PureDarwin/PureDarwin#29]
Originally reported on Google Code with ID 24

```
It doesn't do any harm though.
Looks like, on x86 it seen when using Voodoo's 9.7 kernel.
```

Reported by `me@dukzcry.cc` on 2014-05-25 10:39:21

**Comment by libsystem-ethan** [comment]
> I think this should be closed now as irrelevant. PowerPC Support has long gone extinct for macOS and the project's (PureDarwin) interest has switched to building a working 10.13.3.

Closed.
