### ISSUE TITLE
Use of Travis-CI

### ISSUE THREAD

**Issue by ghost** [PureDarwin/PureDarwin#3]
Following on from the end of #1, I wonder if Travis CI would be useful. Looking at the way the PureDarwin project is currently set up I don't think it's as easy as flicking a switch but perhaps there's some smaller components that can be built using Travis' OS X support?

**Comment by vmlemon** [comment]
Good question - depending on how much control we get over build arguments, we could probably try doing things like various drivers, or occasional contributions of things like X11 server releases, to begin with.

**Comment by hideout** [comment]
indeed, but I have to laugh a little bit because of drivers
too much blockers ;(( but yeah at the x11 server releases and other things
like drivers of course too it make sense

2015-07-08 9:57 GMT+02:00 Tyson Key <notifications@github.com>:

**Comment by vmlemon** [comment]
I'd have said things like MacZFS (that DTM's working on) - but they've already got build infrastructure, and I think we can just use their KEXTs, without doing anything special.

**Comment by hideout** [comment]
Ah ok i understand ...that works.

2015-07-08 10:01 GMT+02:00 Tyson Key <notifications@github.com>:

**Comment by voltagex** [comment]
Looks like OS X builds are currently disabled - see http://docs.travis-ci.com/user/multi-os/

I have sent an email asking for more information.

**Comment by voltagex** [comment]
Aha, got it. https://travis-ci.org/voltagex/mac-test

**Comment by hideout** [comment]
perfect!

2015-07-08 11:22 GMT+02:00 Adam Baxter <notifications@github.com>:

**Comment by mdaniel** [comment]
These issues don't feel like "issues" to me; they feel like people using issues like a mailing list. I thought there was already a mailing list: https://groups.google.com/forum/?fromgroups#!forum/puredarwin ?

**Comment by vmlemon** [comment]
Hah, yeah - I don't know why we're using the issue tracker as a mailing list, either. Confusingly, we also have a list of semi-issues on the old Google Code project...

**Comment by voltagex** [comment]
You're right of course. Github Issues was just easier to use.

**Comment by hideout** [comment]
github ftw! ;)

**Comment by ninjadev64** [comment]
This would actually be really useful to ease new contributors into the project; finding usable ISOs etc is really disorganised right now, with some things in a random Google code repo, some things in one GitHub repo, some in another, etc

**Comment by probonopd** [comment]
Travis CI is no longer a viable option. But GitHub Actions is now available, and it even has Mac instances.

**Comment by ninjadev64** [comment]
Well, then, GitHub actions!

**Comment by ninjadev64** [comment]
+:confused:
