### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by raeesbhatti** [PureDarwin/PureDarwin#30]
This is such a wonderful idea but seems like it has been stalled. Are you guys still interested this project? Do you have any plans?

**Comment by pedrohex** [comment]
Hi !

Not stalled at all , please join #puredarwin at freenode for more information.

Thanks

On 31 Oct 2016, at 22:17, Raees Bhatti <notifications@github.com<mailto:notifications@github.com>> wrote:


This is such a wonderful idea but seems like it has been stalled. Are you guys still interested this project? Do you have any plans?

**Comment by csekel** [comment]
Issue closed, Project is still very active a lt of disscussion and work is being talked about on #puredarwin at freenode. So please join us there. Thanks PD Project!
