### ISSUE TITLE
Release a working ISO ASAP

### ISSUE THREAD

**Issue by mcandre** [PureDarwin/PureDarwin#35]
The "impurities" can be removed later. Is there a working ISO that can be released, for developers to play with?

**Comment by fubarhouse** [comment]
And a Dockerfile maybe?

**Comment by csekel** [comment]
We will be releasing ISO shortly. Thanks

**Comment by csekel** [comment]
https://youtu.be/oCYpCOq0RJg

**Comment by PeterDaveHello** [comment]
Good news!!

**Comment by andreiw** [comment]
Happy to see progress

A

**Comment by benjamingr** [comment]
What happened?

**Comment by hideout** [comment]
What you mean?



Am Do., 12. Dez. 2019 um 22:48 Uhr schrieb Benjamin Gruenbaum <
notifications@github.com>:

**Comment by piranna** [comment]
Any updates on this? It was one and a half years since it was anounced the ISO "soon"...

**Comment by hideout** [comment]
yes we are on this .... stay tuned!

Am Sa., 18. Jan. 2020 um 22:52 Uhr schrieb Jesús Leganés-Combarro <
notifications@github.com>:

**Comment by piranna** [comment]
> yes we are on this .... stay tuned!

Cool! :-D This and the instruction style Linux from Scratch are my main interested ones :-D

**Comment by Oleg26Dev** [comment]
Hey, 
what about ISO? Docker image?

**Comment by Patronics** [comment]
Any news? Now it's been nearly 3 years since the original "soon"

**Comment by ninjadev64** [comment]
Still nothing…..

**Comment by Daasin** [comment]
+1 
Bumping this because it would be cool to have a new bleeding edge iso or docker for testing :)

**Comment by arestifo** [comment]
Any updates?

**Comment by joaquinvacas** [comment]
Anything else?

**Comment by ninjadev64** [comment]
There's a [VMDK](https://github.com/PureDarwin/PD-17.4-Beta) for v17.4, supplied with instructions for converting it to an ISO. Not sure how well it runs on real hardware though. @beeselmane has made progress on building the kernel with a new build system, and it now works mostly fine in place of the factory-shipped XNU in macOS.

Maybe someone on [the Discord server](https://discord.gg/9kz8XXRRcT) knows more. @arestifo @joaquinvacas

**Comment by KevDoy** [comment]
https://www.puredarwin.org/wiki/#/news/_News
