### ISSUE TITLE
build PureDarwin failed

### ISSUE THREAD

**Issue by maldiohead** [PureDarwin/PureDarwin#42]
<img width="694" alt="wx20181010-173957 2x" src="https://user-images.githubusercontent.com/23315692/46727688-aee11900-ccb3-11e8-8880-22c780c98648.png">

what should i do?

**Comment by csekel** [comment]
This is an old version you are trying to use.

**Comment by maldiohead** [comment]
Please give me a document about how to build PureDarwin .I can’t find a full document and the newest one

Best Regards !



Weibo Wang

________________________________

**Comment by csekel** [comment]
We don't have one, yet we are working on updating our current image to latest sources. Once we have that we will provide a doc/video on building PureDarwin.

**Comment by maldiohead** [comment]
Okay.what’s the time will  release the doc,I think it’s very important for Puredarwin .

Best Regards !



Weibo Wang

________________________________

**Comment by maldiohead** [comment]
![image](https://user-images.githubusercontent.com/23315692/46932529-ba9d5880-d082-11e8-833e-7a9f237c1ff0.png)

oops.  seems something wrong!

**Comment by csekel** [comment]
It doesn't just build an OS and there you go, there's a lot of work involved we are working on a new vm to release. Please contact us via email see puredarwin.org for contact details.
