### ISSUE TITLE
vmware.gif link broken

### ISSUE THREAD

**Issue by mcandre** [PureDarwin/PureDarwin#44]
The markdown syntax appears to be invalid for the vmware.gif image link on https://github.com/PureDarwin/PureDarwin/wiki/vmware .

**Comment by x3haloed** [comment]
Not only is the syntax invalid, I think the URI is invalid. I don't see vmware.gif in the repo anywhere. Maybe it was hosted on Google Code before the transition?

**Comment by KevDoy** [comment]
wiki moved to https://www.puredarwin.org/wiki/#/
vmware.gif has been removed in https://github.com/PureDarwin/puredarwin.github.io/pull/27
