### ISSUE TITLE
Window Maker

### ISSUE THREAD

**Issue by mindingulove** [PureDarwin/PureDarwin#45]
Is there any way of installing a GUI in PureDarwin like WindowMaker? That would make it an Spiritual Openstep Sucessor. Thank you

**Comment by wjk** [comment]
In a word, no. We are nowhere near even _considering_ a GUI at this point. Furthermore, the GUI toolkits that work on Linux (WindowMaker included) aren't compatible with non-Linux kernels, such as the XNU kernel used by PureDarwin. Thank you for your question.

**Comment by espectalll** [comment]
Why not? WindowMaker actually works on some BSDs, I don't think it needs that many dependencies - so at the very least, as long as X11 works, it should run on PureDarwin as well, right?

**Comment by d0gb0ne** [comment]
Hello,

Could you subscribe Frank Verhoog from this mailinglist please?
He passed away the 7th of may. And i cannot do it, because i don't have his
Login codes.

Kind regards,

Maaike van Hooff

**Comment by d0gb0ne** [comment]
Hello,

Could you please unsubscribe Frank Verhoog from the mailinglist?
He passed away the 7th of may 2018, and i  don't have his logincodes.

Kind regard,
Maaike van Hooff

**Comment by hideout** [comment]
ok i will unsubscribe later

thanks for your info and all the best to you sorry to hear he passed away

ferdinand

Am Mo., 3. Dez. 2018 um 16:38 Uhr schrieb d0gb0ne <notifications@github.com
