### ISSUE TITLE
Older issues trapped on Google Code

### ISSUE THREAD

**Issue by vmlemon** [PureDarwin/PureDarwin#5]
Whilst we're in the process of revamping infrastructure, I've just remembered that we've got quite a lot of [issue data](https://code.google.com/p/puredarwin/issues/list?can=1&q=&colspec=ID+Type+Status+Priority+Milestone+Owner+Summary&cells=tiles) in the old Google Code project, that will likely get lost, when that service is finally closed down.

Given how poorly their wiki export tool worked, when I last tried it, I don't know if their issue export tool is any better, but Google have made it available at
https://code.google.com/p/support-tools/wiki/IssueExporterTool, for the time being.

**Comment by probonopd** [comment]
Converted
