### ISSUE TITLE
Discussion: Consider migrating away from darwinbuild

### ISSUE THREAD

**Issue by wjk** [PureDarwin/PureDarwin#53]
While darwinbuild has served us well so far, as I work towards building an ISO from scratch (cf #38), I find that it is not well-suited for building a complete Darwin OS image from source. The main issue is that it is stateless. There is no way to tell _a priori_ that a given project has already been built. Because of this, the only way I could implement `darwinbuild -recursive` is to blindly build all detected dependencies every time. This is wasteful of time if invoked repeatedly, as it has no way to tell if a project is up-to-date. As far as darwinbuild knows, it may be wildly out-of-date and therefore must be rebuilt, even though _we_ know it was just built two minutes ago by a previous darwinbuild invocation. Furthermore, the use of darwinbuild plists to orchestrate the build does not work well with any sort of CI system; it is also IMHO a very chaotic method to handle versioning of dependencies. All the changes made to [PD18_2.plist](https://github.com/PureDarwin/PureDarwin/commits/master/plists/PD18_2.plist) also required a tag be made in the source repository, a completely ad-hoc and non-standardized process.

In addition, I am growing personally disillusioned with the increasingly locked-down nature of Apple macOS. As a result, I was looking into ways to potentially build PureDarwin without needing to use xcodebuild, as Xcode requires the use of macOS. (Yes, there is xcbuild, but while it once showed promise it is now so bit-rotten that it no longer works at all due to changes in Xcode; furthermore, even when it was comparable in functionality with Apple xcodebuild, it had a nasty habit of segfaulting.) The Darling project uses CMake to build a Darwin-esque environment (everything but kernel-mode) from source using CMake. While one benefit of this technique is that it works on Linux as well on Darwin/macOS, I feel that moving PureDarwin to a build system like Darling's (using CMake and possibly a vendored copy of cctools/ld64), and using submodules to organize the code would have benefits even if we stick to building PureDarwin on macOS (or itself!) only.

If this proposal is accepted, I would start work by creating an "SDK" repository that contains the common CMake modules that handle things such as cross-compiling or processing MIG files, as well as a copy of the headers and `*.tbd` stub library files that are used to build an arbitrary PureDarwin component. (This would essentially be a freely-licensed version of the Xcode MacOSX.sdk directory.) I would then add CMakeLists.txt files to the various repositories under the PureDarwin organization. Once that's done, I would add those repositories as submodules under the `projects/` directory. When the root PureDarwin repo is cloned, the SDK would be included as a submodule and the other projects would be pointed to it via a CMake variable. (If a component repo is cloned on its own, for example in a CI scenario, then the SDK would need to be downloaded separately before the build and CMake given its location manually.)

The build process for XNU would not change much. XNU will still be built using the existing Makefile-based system, integrated into the CMake build using the [ExternalProject](https://cmake.org/cmake/help/v3.16/module/ExternalProject.html) system. Its dependencies (dtrace, libdispatch, and a few others) would be built using CMake, and passed into the XNU makefiles using a file containing paths generated using the CMake `configure_file` feature.

Tell me what you think!

**Comment by csekel** [comment]
The way darwinbuild worked in the past was was with chroot and when projects were built it was in a self contained Ecosystem It would copy enough of the OS to be command line and work with Xcode and build projects and Darwinbuild would look in the DB for Projects that were built (completed successfully). Using the Plist for each major release was the way to at the time like we really should be using 18_3 now for the 10.14.3 code that was released. 

I do like your idea on moving to CMake but we are talking about every project Apple or others release being moved(created) from Xcode. I know with plist you could pass patches and define project headers requirements like code-sign and such.  I always found it easier to maintain plist and make patches as necessarily needed.  

If you want to start this adventure I would suggest Creating a new Repo to work from Working from within PureDarwin Main Repo should not happen any longer. I just don’t want massive changes to be made and this path doesn’t work out. 

Let me know what you want to do.

**Comment by wjk** [comment]
After further reflection I have decided against of the use of CMake. I was not able to get the required compiler tools to compile correctly on Linux (via Docker), which defeats the point of using CMake over Xcode. Your concerns about using a different repo for large changes are noted. I'll probably use my [old "Andromeda" org](https://github.com/Andromeda-OS) as a staging area for ideas such as these. Thanks!

**Comment by brunomaximom** [comment]
@wjk why not adapt the Free or NetBSD build system to build a useful BSD Darwin system resyncing the FreeBSD bits to the latest ones or switching to NetBSD for portability issues?

**Comment by wjk** [comment]
@brunomaximom I've actually looked into using a loadable kernel module on top of FreeBSD-current to handle the parts of PureDarwin that must be done in kernel-space, plus a user-mode loader in place of DYLD. I worked on this for a few weeks, but decided to shelve it in favor of continuing to use XNU; I never made it to work fully. [You can find the code here.](https://github.com/Andromeda-OS/mach-loader-freebsd) As for merging FreeBSD code into XNU itself, that's impossible. XNU has simply diverged too much from upstream FreeBSD, not to mention all the components that Apple has written from scratch.

However, apart from that, I have not found any other build system other than Xcode’s that would be usable for building PureDarwin, due to the fact that PureDarwin will (eventually) include components that require the Xcode build system to successfully compile (such as applications or Foundation-level frameworks). I could attempt to use CMake to generate an Xcode project, but this would entail a lot of extra work to get the same end result. Furthermore, darwinbuild currently runs on a vanilla macOS box with no dependencies other than the Xcode tools, while CMake must be installed separately. Therefore, this project will be sticking with the status quo of darwinbuild and Xcode for the foreseeable future.

**Comment by brunomaximom** [comment]
> As for merging FreeBSD code into XNU itself, that's impossible. XNU has simply diverged too much from upstream FreeBSD
Yes, I don't think resync FreeBSD kernel code into XNU is possible. I was talking about the FreeBSD userland in Darwin (all the Unix commands) which came from FreeBSD.

> not to mention all the components that Apple has written from scratch.
Yep, I remember when I was looking the Darwin's top command. It's completely written from scratch and refers to many Mach features, so the Mach-dependant code must to come from Apple. But anyway, I think resync the userland commands to the latest FreeBSD is possible.

> (such as applications or Foundation-level frameworks)
Is Foundation framework really necessary to build an useful Unix OS?

I have 2 questions about the actual scenario:
1. How you'll manage APFS?
2. What about the new DriverKit?

**Comment by wjk** [comment]
We can certainly look into updating the userland tools, once we have a userland to update. (Currently we're still working on the boot procedure and very-low-level libraries.) There are several third-party APFS implementations, some freely licensed, some proprietary. We've yet to look into it. DriverKit, on the other hand, can be reimplemented just like any other API.

**Comment by cooljeanius** [comment]
so I used to use DarwinBuild via the port in MacPorts for it on my old computer, but now that I have a new computer, the darwinbuild port no longer builds because it tries to build universal (64+32bit), but compiling for 32bit is no longer supported on Catalina, so it fails. If the project intends to continue to use darwinbuild, I would recommend updating the port for it in MacPorts so that it continues to work with Catalina. Otherwise, I would agree with the original suggestion to move away from darwinbuild.

**Comment by wjk** [comment]
@cooljeanius We don't use the darwinbuild in MacPorts; we use [our own fork](https://github.com/PureDarwin/darwinbuild). This version has many necessary changes and fixes that are PureDarwin-specific. Please try that version instead. Thanks!

**Comment by johnothwolo** [comment]
@wjk Here's a substitute for xcodebuild https://github.com/darwin-on-arm/darwin-sdk. What do you think?

**Comment by barracuda156** [comment]
> so I used to use DarwinBuild via the port in MacPorts for it on my old computer, but now that I have a new computer, the darwinbuild port no longer builds because it tries to build universal (64+32bit), but compiling for 32bit is no longer supported on Catalina, so it fails.

@cooljeanius Just remove default `+universal` in the portfile. It does build for a single arch then. (Though remains broken for PPC atm.)

**Comment by barracuda156** [comment]
> @cooljeanius We don't use the darwinbuild in MacPorts; we use [our own fork](https://github.com/PureDarwin/darwinbuild). This version has many necessary changes and fixes that are PureDarwin-specific. Please try that version instead. Thanks!

@wjk Has it been fixed for PPC or it remains broken?

**Comment by cooljeanius** [comment]
So, I see Barracuda already commented on the other end of this, but, just for cross-referencing purposes, my MacPorts-side issue for updating their version to the PureDarwin version is here: https://trac.macports.org/ticket/60817

**Comment by barracuda156** [comment]
> So, I see Barracuda already commented on the other end of this, but, just for cross-referencing purposes, my MacPorts-side issue for updating their version to the PureDarwin version is here: https://trac.macports.org/ticket/60817

@cooljeanius I will try building that, though I suspect much has to be done to make it work on Darwin PPC.
