### ISSUE TITLE
Discussion: Is this project dead?

### ISSUE THREAD

**Issue by hoper-a11y** [PureDarwin/PureDarwin#55]
I have keep an eye on this project for a long time without seeing any usable yet. The deveopment speed seemed to be very slow, too. The developers used to said this project is just for fun. So I think it's not a serious project? Do I expect too much from this project? What is the current status of it? Please let me know.

**Comment by hideout** [comment]
Hey!

It is a Serious Project.
And we have fun at our Work ofc everybody is in their real work busy at the
moment.
So´stay tuned you will see progress soon,.

Thanks for supporting our Project!

Ferdinand

Am Do., 25. Juni 2020 um 11:58 Uhr schrieb hoper-a11y <
notifications@github.com>:
