### ISSUE TITLE
Discussion: Could you switch from QEMU to VirtualBox?

### ISSUE THREAD

**Issue by hoper-a11y** [PureDarwin/PureDarwin#56]
Currently it seemed you only provide image for plain QEMU. VirtualBox is more user friendly and has more users than QEMU. Most of the experimental OS also used VirtualBox for the development image, e.g: ReactOS, HaikuOS,... so your decision to use QEMU is a bit weird. Please consider switch to VirtualBox or at least support VirtualBox alongside of QEMU. Thanks.

**Comment by vmlemon** [comment]
If I remember correctly, there are some issues with certain drivers, and the boot process, that break things, in VirtualBox, right now.

**Comment by hideout** [comment]
Hi,

indeed Tyson did already a lot of testing and hoper-a11y would be nice to
have a real name from you
and then join #puredarwin at Freenode irc (irc.kde.org as a example) i am
bart

cheers ferdinand



Am Do., 25. Juni 2020 um 12:03 Uhr schrieb Tyson Key <
notifications@github.com>:

**Comment by EchedeyLR** [comment]
> Currently it seemed you only provide image for plain QEMU. VirtualBox is more user friendly and has more users than QEMU. Most of the experimental OS also used VirtualBox for the development image, e.g: ReactOS, HaikuOS,... so your decision to use QEMU is a bit weird. Please consider switch to VirtualBox or at least support VirtualBox alongside of QEMU. Thanks.

You can always use a QEMU front-end like Virt Manager which is user friendly and with better features than VirtualBox.
