### ISSUE TITLE
Hi, where is the VirtualBox images?

### ISSUE THREAD

**Issue by gh-legacy** [PureDarwin/PureDarwin#58]
I didn't found any.

**Comment by csekel** [comment]
The VM images are linked on the PureDarwin.org page under beta.

**Comment by gh-legacy** [comment]
> The VM images are linked on the PureDarwin.org page under beta.

Thank you. I have downloaded both PD 17.4 and Xmas but I can't get them working on VirtualBox.

Xmas hang at System model name: iMac8,1

PD 17.4 hang at Still waiting for root device

Please let me know what is the recommended setting for the VM. Thanks.

**Comment by csekel** [comment]
Qemu *

**Comment by gh-legacy** [comment]
> Qemu *

Qemu with KVM or plain Qemu?

**Comment by gh-legacy** [comment]
Finally I found the right guide and could have PD 17.4 booting for me: https://www.jamieweb.net/blog/a-look-at-puredarwin/

Still have incompatibilities, though. I couldn't use nano to edit even a simple text file since the screen will be messed up.

I still have no luck with Xmas, though. Even though I have read it was originally designed to work on VirtualBox and I have saw many screenshots of it running under Vbox, I can't make it work on my Vbox 6.

The guide here is missing from the current wiki: https://sites.google.com/a/puredarwin.org/puredarwin/developers/virtualbox

Even if I followed it, Xmas still doesn't boot. Another issue is both Xmas and PD 17.4 definitely will not boot with EFI on on Vbox.

**Comment by csekel** [comment]
PD 17.4 Is BIOs based not EFI hence why you need to follow this command to boot it in qemu..

qemu-system-x86_64 -m 8192 -cpu Penryn -smp 2 -netdev user,id=network0 -device rtl8139,netdev=network0 -serial stdio -drive format=vmdk,file=pd_17_4.vmdk
