### ISSUE TITLE
Update plists

### ISSUE THREAD

**Issue by probonopd** [PureDarwin/PureDarwin#6]
Update plists to use GitHub, both for PureDarwin and upstream sources.

For example, the osxbom upstream code is now on GitHub
https://github.com/cooljeanius/osxbom/archive/0.0.4.tar.gz

**Comment by wyatt8740** [comment]
I can help with this over the weekend, I think. I'll keep you posted if I can.

**Comment by hideout** [comment]
thanks!

2016-01-13 14:47 GMT+01:00 Wyatt Ward <notifications@github.com>:

**Comment by cooljeanius** [comment]
> Update plists to use GitHub, both for PureDarwin and upstream sources.
> 
> For example, the osxbom upstream code is now on GitHub
> https://github.com/cooljeanius/osxbom/archive/0.0.4.tar.gz

so just to clarify, I'm not the original "upstream" of osxbom; I just forked it to mess around with it. But I'm flattered that you find my fork useful!

**Comment by csekel** [comment]
@cooljeanius Thanks we are working new plist we'll except any ones help to update the old plist with new links. as needed.

**Comment by ninjadev64** [comment]
Was any progress made on this?

**Comment by cooljeanius** [comment]
> > Update plists to use GitHub, both for PureDarwin and upstream sources.
> > For example, the osxbom upstream code is now on GitHub
> > [cooljeanius/osxbom@`0.0.4`.tar.gz](https://github.com/cooljeanius/osxbom/archive/0.0.4.tar.gz)
> 
> so just to clarify, I'm not the original "upstream" of osxbom; I just forked it to mess around with it. But I'm flattered that you find my fork useful!

N.B. there's now a newer `0.0.5` release: https://github.com/cooljeanius/osxbom/releases/tag/0.0.5
