### ISSUE TITLE
Github description says OS X 

### ISSUE THREAD

**Issue by ShalokShalom** [PureDarwin/PureDarwin#63]
Hi 🤗

You know you still say OS X instead of macOS in the title?
Just asking, maybe you forgot. Dont wanna nagging 😊

**Comment by hideout** [comment]
lol no we didnt forgot..  but our latest release is. still based on mac. os
x!

Am Di., 24. Nov. 2020 um 19:46 Uhr schrieb ShalokShalom <
notifications@github.com>:

**Comment by wyatt8740** [comment]
There's also the fact that humans will recognize both names and it doesn't really matter.

**Comment by ShalokShalom** [comment]
I think in case it is really based on OS X, I actually prefer it the way it is. Just add the version number?

**Comment by wjk** [comment]
Done.
