### ISSUE TITLE
How to build? Missing crt_externs.h

### ISSUE THREAD

**Issue by scrouthtv** [PureDarwin/PureDarwin#65]
Hello,

I am currently working on a project which should also be available for macOS devices.
I don't want to buy an apple product, but I think this is the right place to get a basic working darwin installation.

My question is, how do I build this project? Or can I get a pre-built iso somewhere?
I cloned the repo and ran `cmake . && make`.
After some time, make failed:

```
[  9%] Completed 'cctools_host.extproj'
[  9%] Built target cctools_host.extproj
[  9%] Creating VersionMap.h and for_dyld_priv.inc
Scanning dependencies of target dyld_availability_headers
[ 10%] Building C object projects/AvailabilityVersions/CMakeFiles/dyld_availability_headers.dir/dummy.c.o
[ 10%] Linking CROSS static library libdyld_availability_headers.a
[ 10%] Built target dyld_availability_headers
Scanning dependencies of target libelf.host
[ 11%] Building C object tools/dtrace_ctf/libelf/CMakeFiles/libelf.host.dir/begin.c.o
/mnt/d/code/cross/PureDarwin/tools/dtrace_ctf/libelf/begin.c:43:10: fatal error: 'crt_externs.h' file not found
#include <crt_externs.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [tools/dtrace_ctf/libelf/CMakeFiles/libelf.host.dir/build.make:82: tools/dtrace_ctf/libelf/CMakeFiles/libelf.host.dir/begin.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:597: tools/dtrace_ctf/libelf/CMakeFiles/libelf.host.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

Can I only build this on an existing MacOS? Do I have to install Xcode or something? I can't find any installation / building instructions.

Thanks in advance.

**Comment by scrouthtv** [comment]
Here is another error I got:
```
make[4]: /Users/runner/work/PureDarwin/PureDarwin/projects/xnu/tools/uncrustify.sh: No such file or directory
```

**Comment by scrouthtv** [comment]
And another one:
```
/Users/runner/work/PureDarwin/PureDarwin/projects/xnu/bsd/kern/subr_log.c:77:10: fatal error: 'os/firehose_buffer_private.h' file not found
#include <os/firehose_buffer_private.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by csekel** [comment]
If you look at the dependencies on this plist of Darwinbuild for the latest PD version. Some programs require headers from others which all under opensource.apple.com.
If you look at this plist we have broken down which project requires headers from which and may help you build on whatever Linux distro you are using with cmake. 
 https://github.com/PureDarwin/PureDarwin/blob/master/plists/PD19_0.plist
