### ISSUE TITLE
 Collaboration with the Darling project

### ISSUE THREAD

**Issue by Qib10** [PureDarwin/PureDarwin#70]
Hi
I have a suggestion to merge multiple files from the Darling project, but Darling is still in beta.
[Darling site](https://darlinghq.org)

**Comment by csekel** [comment]
Which files are you referring to?

**Comment by Qib10** [comment]
Like some core component...

**Comment by csekel** [comment]
If they are Linux module bonded it's not possible.

**Comment by Qib10** [comment]
Oh okay
