### ISSUE TITLE
Make Discord Channels

### ISSUE THREAD

**Issue by Qib10** [PureDarwin/PureDarwin#71]
I'm need Discord channels for PureDarwin

It's not issue but i recommeded to make more easy for all developer and user for info and chat

Sorry for bad English 😅

**Comment by csekel** [comment]
We have a telegram channel

**Comment by Qib10** [comment]
Can you share telegram channel link?

**Comment by ninjadev64** [comment]
The Discord server now has over 100 members, and today I've opened a Matrix space - feel free to join at #puredarwin:matrix.org :)
