### ISSUE TITLE
Discussion: Regarding Contributing to the Project

### ISSUE THREAD

**Issue by pizzabug** [PureDarwin/PureDarwin#90]
Hey! I came across this project a few years ago but, I was wondering where I could get started communicating with other developers, and seeing where there are gaps to fill? 

Particularly, I was wondering about these: 
- How many of Apple's binary drivers that PureDarwin relies on has been reimplemented or have become missing over the years as Apple gradually stopped distributing them? Is there some sort of roadmap to completion in terms of binary drivers that potential collaborators have for reference?
   
   _**Update:** Providing a self-answer, a list of required binary drivers can be found here on the [Binary Drivers](https://github.com/PureDarwin/PureDarwin/wiki/BinaryDrivers) page on the wiki. It's not a pretty set of pages but, here's the progress on projects in PureDarwin, built upon [Darwin 10](https://github.com/PureDarwin/PureDarwin/wiki/Darwin_10) and [9](https://github.com/PureDarwin/PureDarwin/wiki/Darwin_9). Tables are pretty unreadable, but it tracks all the projects and how they're building currently. Current blockers can be found [here](https://github.com/PureDarwin/PureDarwin/wiki/Current_Blockers), and on issues as well._

- Do we have some reference on how to build the whole PureDarwin stack? Do we need an x86_64 macOS machine to do so, or are there possible alternatives? I currently have one of the new arm64 M1 Macs (and multiple x86_64 Linux machines, but that's besides the point).

   _**Update:** If the [homepage](http://www.puredarwin.org/) is still updated, we're at XNU 16.7(10.12.6). Build guide is [here](https://github.com/PureDarwin/Building-XNU-16.7-Kernel-Guide/). For unsupported platforms, it's not possible until an open-source alternative for `iig` from the [DriverKit SDK](https://developer.apple.com/documentation/driverkit/creating_a_driver_using_the_driverkit_sdk) is implemented. In terms of how to begin doing so, someone could fork [Darwin on ARM](https://github.com/darwin-on-arm) on [darwin-sdk](https://github.com/darwin-on-arm/darwin-sdk) and implement `iig`? It is a non-trivial task, however._

- Is there a particular place where we can communicate? The way to access current forms of communication is currently not really obvious or down. The forums have been down for a bit and I'm not too sure how to access the Freenode IRC channel.

I'm sorry if these are very obvious questions and if I sound really pushy, I'm just very interested in the development of the project and I was hoping to ask questions that me and other prospective future collaborators may want to ask to pick up the pace of development.

**Comment by wjk** [comment]
Our code base is not a descendant of any of the old code bases you might find online, nor did we build the ISOs that are floating around the internet. We are not planning any architectural ports at this time, but any attempts at such would be welcome. That being said, there is already plenty to do in the current codebase. Port new Apple packages if you want, or feel free to make the existing code more readable! As far as `iig` goes, please see #92. Thanks everyone!

**Comment by beeselmane** [comment]
Hi, I was wondering something somewhat similar to what the others in this thread were asking, I've looked around the wiki/the rest of this org and on the web generally for info on this project, and it seems that save for @wjk's recent work on this repo/a bit of stuff on darwinbuild, no real work has been put in for a few years. Would anyone be interested in seeing if we can clean up some of the old info on the wiki and working to include Apple's new sources and writing patches to build PureDarwin with modern XNU and system utils (Apple's current Darwin is into major version 20)? I see some work seems to have been put in on this repo, but it doesn't seem quite right, with cmake issues and such.

I'm wondering which of the actual members of this org are still active? It seems @csekel has had some recent activity, as well as one of the other members of the org, but the other members have no commit history for at least the last year. Anyone looking to take another look at this project? I think the idea of an open source *nix system based on the XNU kernel and Apple's userland sources sounds pretty cool.

Is there any info on who the current team is for this project or who to contact with regard to developing it further?

**Comment by ninjadev64** [comment]
Hey beeselmane, if you want you can join the Discord server where the
developers (and the community) are willing to chat.

**Comment by wjk** [comment]
For future reference, darwinbuild is now deprecated. We worked with it for a long time, but I eventually found it too unsuitable for rapid iteration; it was also becoming less and less compatible with macOS as it Apple continued to lock it down. I have therefore marked its repo as archived.

**Comment by ninjadev64** [comment]
@wjk You should be able to convert this issue to a discussion; please could you do that?
